trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Infrastructure/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'EventGridTrigger'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
      
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'